name: save_ai
description: SAVE-AI

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Firebase
  firebase_core: "^0.5.3"
  firebase_auth: "^0.18.4+1"
  google_sign_in: "^4.5.1"
#  flutter_facebook_auth: "^1.0.0"
#  sign_in_with_apple: ^2.5.2
#  crypto: ^2.1.5
#  flutter_twitter_login: ^1.1.0


  # state management
  provider: ^4.3.2+2

  # network requests
  dio: ^3.0.10


  # UI
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.10.0
  animated_text_kit: ^2.5.4
  google_fonts: ^1.0.0
  flutter_staggered_animations: ^0.1.2
  group_button: ^1.1.0 #latest version
  # beauty_textfield: ^0.0.1
  flutter_datetime_picker: ^1.4.0
  city_pickers: ^0.2.0
  giffy_dialog: ^1.8.0
  awesome_dialog: ^1.2.1
  flutter_tags: "^0.4.9+1"
  settings_ui: ^0.4.0
  syncfusion_flutter_calendar: ^18.3.52
  toast: ^0.1.5
  lottie: ^0.6.0
#  cached_network_image: ^2.5.0
#  meet_network_image: ^0.1.2
  network_to_file_image: ^2.3.6
  device_calendar: ^3.1.0
  url_launcher: ^5.7.10
#  sliding_card: ^0.1.2
#  flutter_skeleton: ^0.1.0+1
  flutter_html: ^1.2.0
  image_picker: ^0.6.7
  country_state_city_picker: ^1.2.7
  pull_to_refresh: 1.6.3
  tcard: ^1.3.3
  intl: ^0.16.0








dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/img/LOGO.png
    - assets/images/

  fonts:
    - family: Feather
      fonts:
        - asset: assets/fonts/feather.ttf

    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
